smilepack/utils/urls.py
# -*- coding: utf-8 -*-

from hashlib import md5
from pony import orm

from flask import current_app

from smilepack.models import Smile, SmileUrl


def check_and_normalize(url):
    if not url or not isinstance(url, str):
        raise ValueError('Invalid url')
    if url.startswith('//'):
        url = 'http:' + url
    if not url.startswith('http://') and not url.startswith('https://'):
        raise ValueError('Invalid url {}'.format(url))
    return url


def hash_url(url):
    return md5(url.encode('utf-8')).hexdigest()


def parse_by_regex(url):
    for item in current_app.config['URL_PARSER_REGEX']:
        m = item['re'].search(url)
        if not m:
            continue

        result = {}

        try:
            result['id'] = int(m.group('id'))
        except IndexError:
            pass

        try:
            result['filename'] = m.group('filename')
        except IndexError:
            pass

        if result:
            return result
    return None


def parse(urls):
    parsed_urls = []
    ids = []
    filenames = []

    for url in urls:
        if not url:
            parsed_urls.append({})
            continue
        r = parse_by_regex(url)
        if r:
            parsed_urls.append(r)
            if 'id' in r:
                ids.append(r['id'])
            if 'filename' in r:
                filenames.append(r['filename'])
        else:
            parsed_urls.append({})

    return {
        'parsed_urls': parsed_urls,
        'ids': ids,
        'filenames': filenames
    }


def rehash_custom_smiles(min_id=None, pagesize=500):
    print('Checking duplicates...')
    d = orm.select((x.custom_url, orm.count(x.id)) for x in Smile if x.custom_url is not None).order_by(-1, 2)[:21]
    if d and d[0][1] > 1:
        if len(d) <= 20:
            print('You have {} duplicates:\n{}\nPlease fix it.'.format(
                len(d),
                '\n'.join(' - {} ({})'.format(*x) for x in d)
            ))
        else:
            print('You have more than 20 duplicates. Please fix it.')
        return

    if min_id is None:
        min_id = orm.select(orm.min(x.id) for x in Smile).first()
    if min_id is None:
        print('Nothing.')
        return

    while True:
        smiles = Smile.select(lambda x: x.id >= min_id).order_by(Smile.id)[:pagesize]
        if not smiles:
            break
        print('{}...'.format(smiles[0].id))
        min_id = smiles[-1].id + 1

        orm.commit()

        for smile in smiles:
            if not smile.custom_url:
                continue
            url = smile.url
            url_hash = hash_url(url)

            u = SmileUrl.select(lambda x: x.url_hash == url_hash).first()
            if u:
                if u.url != url:
                    u.url = url
                if u.smile != smile:
                    u.smile = smile
                u.flush()
            else:
                u = SmileUrl(
                    url_hash=url_hash,
                    url=url,
                    smile=smile
                ).flush()

smilepack/views/pages.py
# -*- coding: utf-8 -*-

from hashlib import md5

from pony.orm import db_session

from flask import Blueprint, Response, render_template, abort, current_app, request, redirect, url_for
from flask_babel import format_datetime

from smilepack.models import Section, SmilePack, Smile, Icon
from smilepack.views.utils import user_session, for_admin


bp = Blueprint('pages', __name__)


@bp.route('/')
@user_session
@db_session
def index(session_id, first_visit):
    smiles_count = Smile.bl.get_all_collection_smiles_count()

    # TODO: переделать с учётом удаления старых смайлопаков
    smilepacks_count = current_app.cache.get('smilepacks_count')
    if smilepacks_count is None:
        smilepacks_count = SmilePack.select().count()
        current_app.cache.set('smilepacks_count', smilepacks_count, timeout=300)

    smilepacks = SmilePack.bl.get_by_user(session_id) if not first_visit else []
    smilepacks.reverse()
    return render_template(
        'index.html',
        session_id=session_id,
        first_visit=first_visit,
        smilepacks=smilepacks,
        smiles_count=smiles_count,
        smilepacks_count=smilepacks_count,
        new_smiles_json=Smile.bl.get_last_approved_as_json(count=25)
    )


@bp.route('/generate', defaults={'smp_hid': None, 'version': None})
@bp.route('/generate/<smp_hid>', defaults={'version': None})
@bp.route('/generate/<smp_hid>/<int:version>')
@user_session
def generator(session_id, first_visit, smp_hid, version):
    if smp_hid:
        with db_session:  # workaround for add_view (TODO: recheck this)
            packs = SmilePack.bl.get_versions(smp_hid)
            if not packs:
                abort(404)
            pack = None
            for x in packs:
                if version is not None and x.version == version:
                    pack = x
                    break
                elif not version and (not pack or x.version > pack.version):
                    pack = x
            if not pack:
                abort(404)
            pack.bl.add_view(request.remote_addr, session_id)
            pack_id = pack.id
            packs = [x.id for x in packs]
    else:
        pack = None
        pack_id = None
        packs = []

    with db_session:
        pack = SmilePack.get(id=pack_id) if pack_id is not None else None
        packs = SmilePack.select(lambda x: x.id in packs).order_by(SmilePack.version) if packs else []
        return render_template(
            'generator.html',
            session_id=session_id,
            can_edit=pack and pack.user_cookie == session_id,
            first_visit=first_visit,
            pack=pack,
            versions=packs,
            pack_deletion_date=format_datetime(pack.delete_at) if pack and pack.delete_at else None,
            lifetime=(pack.delete_at - pack.created_at).total_seconds() if pack and pack.delete_at else None,
            icons=Icon.bl.select_published()[:],
            icon_size=current_app.config['ICON_SIZE'],
            collection_data={"sections": Section.bl.get_all_with_categories()},
        )


@bp.route('/view/<smp_hid>', defaults={'version': None})
@bp.route('/view/<smp_hid>/<int:version>')
@user_session
def view(session_id, first_visit, smp_hid, version):
    if smp_hid:
        with db_session:
            packs = SmilePack.bl.get_versions(smp_hid)
            if not packs:
                abort(404)
            pack = None
            for x in packs:
                if version is not None and x.version == version:
                    pack = x
                    break
                elif not version and (not pack or x.version > pack.version):
                    pack = x
            if not pack:
                abort(404)
            pack.bl.add_view(request.remote_addr, session_id)
            pack_id = pack.id
            packs = [x.id for x in packs]
    else:
        pack = None
        pack_id = None
        packs = []

    with db_session:
        pack = SmilePack.get(id=pack_id) if pack_id is not None else None
        packs = SmilePack.select(lambda x: x.id in packs).order_by(SmilePack.version) if packs else []
        return render_template(
            'view.html',
            session_id=session_id,
            first_visit=first_visit,
            pack=pack,
            versions=packs,
            pack_deletion_date=format_datetime(pack.delete_at) if pack and pack.delete_at else None,
            lifetime=(pack.delete_at - pack.created_at).total_seconds() if pack and pack.delete_at else None,
        )


@bp.route('/admin/')
@db_session
@for_admin
def admin():
    return render_template(
        'admin.html',
        icons=Icon.bl.select_published()[:],
        admin_icons=Icon.select()[:],
        icon_size=current_app.config['ICON_SIZE'],
    )


@bp.route('/setlocale', methods=['GET', 'POST'])
def setlocale():
    locale = request.form.get('locale')
    if locale not in current_app.config['LOCALES']:
        locale = 'en'
    response = current_app.make_response(redirect(url_for('.index')))
    response.set_cookie('locale', locale, max_age=3600 * 24 * 365 * 10)
    return response


@bp.route('/robots.txt', methods=['GET'])
def robots():
    hosthash = md5(request.url_root.encode('utf-8')).hexdigest()
    data = current_app.cache.get('robots_' + hosthash)
    if not data:
        with db_session:
            data = render_template('robots.txt')
        current_app.cache.set('robots_' + hosthash, data, timeout=3600 * 24)
    return Response(data, mimetype='text/plain; charset=utf-8')


@bp.route('/sitemap.xml', methods=['GET'])
@db_session
def sitemap():
    hosthash = md5(request.url_root.encode('utf-8')).hexdigest()
    data = current_app.cache.get('sitemap_' + hosthash)
    if not data:
        with db_session:
            last_smile = Smile.bl.get_last_approved(count=1)
            last_smile = last_smile[0] if last_smile else None
            data = render_template('sitemap.xml', last_modified=last_smile.updated_at if last_smile else None)
        current_app.cache.set('sitemap_' + hosthash, data, timeout=300)
    return Response(data, mimetype='text/xml; charset=utf-8')

smilepack/views/settings.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import jsonschema
from pony.orm import db_session
from flask import Blueprint, render_template, request, redirect, url_for
from flask_babel import gettext
from flask_login import current_user

from smilepack.views.utils import csrf_protect
from smilepack.utils.exceptions import BadRequestError


bp = Blueprint('settings', __name__)


@bp.route('/settings/', methods=['GET', 'POST'])
@csrf_protect
@db_session
def settings_page():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login_page'))

    if request.method != 'POST':
        return render_template('settings.html')

    errors = []

    if request.form.get('password1'):
        if request.form.get('password1') != request.form.get('password2'):
            errors.append(gettext('Passwords do not match'))
        elif not current_user.bl.authenticate(request.form.get('current_password')):
            errors.append(gettext('Current password is incorrect'))
        else:
            try:
                # User.bl.set_password() has no validation
                current_user.bl.edit({'password': request.form.get('password1')})
            except jsonschema.ValidationError as exc:
                errors.append(exc.message)
            except BadRequestError as exc:
                errors.append(str(exc))  # TODO: gettext later

    return render_template('settings.html', errors=errors, ok=not errors), (422 if errors else 200)

smilepack/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <title>{{ _("Smilepack") }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=yes" />
    {{ favicon_link_tag() }}
    {{ stylesheet_tag("landing_css") | safe }}
</head>
<body>

<div class="main">
    <h1 class="sitename">{{ _("Yes, it is smilepack!") }}</h1>
    <div class="stat">
        {{ ngettext("%(num)d smile in collection,", "%(num)d smiles in collection,", smiles_count) }}
        {{ ngettext("%(num)d smilepack created", "%(num)d smilepacks created", smilepacks_count) }}
    </div>

    <div class="actions-panel">
    {% if current_user.is_authenticated %}
        {{ _("Logged in as {username}").format(username=current_user.username) }}
        <form class="inline-form" method="POST" action="{{ url_for('auth.logout_page') }}">
            {{ csrf_token_field() }}
            <input type="submit" class="landing-button" value="{{ _('Log out') }}" />
        </form><br/>

        {% if current_user.is_admin %}<a href="{{ url_for('pages.admin') }}">{{ _('Smilepack administration') }}</a>{% endif %}
        <a href="{{ url_for('settings.settings_page') }}">{{ _('Profile settings') }}</a>
    {% endif %}
    </div>

    <div class="main-action-panel">
        <a href="{{ url_for('pages.generator') }}" class="landing-button generate-button">{{ _("Create smilepack") }}</a>
    </div>
    {% if smilepacks %}
    {{ _("Or open an existing one:") }}
    <ul class="smilepacks-list">
    {%- for pack in smilepacks %}
        <li><a href="{{ url_for('pages.generator', smp_hid=pack.hid) }}">{{pack.name or pack.hid}}</a> <time class="smp-date" datetime="{{ pack.created_at.strftime('%Y-%m-%dT%H:%M:%SZ') }}">({{ pack.created_at|datetimeformat }})</time></li>
    {% endfor %}
    </ul>
    {% endif %}
</div>

<div class="additional">
    {%- if new_smiles_json|length >= 20 %}
    <div class="new-smiles-container">
        <div class="new-smiles-title">{{ _("New smiles:") }}</div>
        <div id="new-smiles" class="new-smiles">{% for smile in new_smiles_json %}
            <a href="{{ url_for('pages.generator') }}#{{ smile['category'][0] }}"><img src="{{ smile['url'] }}" alt="" title="{{ smile['category'][1] }}" /></a>
        {%- endfor %}</div>
    </div>
    {% endif -%}
</div>

<div class="footer">
{% if config['ISSUE_REPORT_LINK'] -%}
    <a href="{{ config['ISSUE_REPORT_LINK'] }}" target="_blank" class="report-link">{{ _("Report an issue") }}</a>
{%- endif %}
<form class="locale-form" method="POST" action="{{ url_for('pages.setlocale') }}">
    <select name="locale">
    {% for locale, title in config['LOCALES']|dictsort %}
        <option value="{{ locale }}"{{ ' selected' if locale == g.locale.language else '' }}>{{ title }}</option>
    {% endfor %}
    </select>
    <input type="submit" class="locale-submit" value="OK" />
</form>
</div>

{{ javascript_tag("landing_js") | safe }}
</body>
</html>

smilepack/templates/login.html
{% extends 'simple_page.html' %}
{% block modal_body %}
<div class="modal-title">{{ _("Staff Only") }}</div>
{% with messages = get_flashed_messages() %}
  {% for message in messages %}
    <em>{{ message }}</em><br/>
  {% endfor %}
{% endwith %}
<form method="POST" action="{{ url_for('auth.login_page') }}">
  {{ csrf_token_field() }}

  <label for="username">{{ _("Username") }}:</label><br/>
  <input type="text" name="username" class="text input-width-full" value="{{ username }}" /><br/>

  <label for="password">{{ _("Password") }}:</label><br/>
  <input type="password" name="password" class="text input-width-full" /><br/>

  <label><input type="checkbox" name="remember" value="1" checked /> {{ _('Remember Me') }}</label><br/>

  <input type="submit" class="button button-primary" value="{{ _('Log In') }}" />
</form>
{% endblock %}

smilepack/templates/settings.html
{% extends 'simple_page.html' %}
{% block modal_body %}
<div class="modal-title">{{ _("Profile settings") }}: {{ current_user.username }}</div>
{% if errors %}
    {% for error in errors %}
        <em>{{ error }}</em><br/>
    {% endfor %}
{% endif %}
{% if ok %}
    <em>{{ _('Saved!') }}</em><br/>
{% endif %}
<form method="POST" action="{{ url_for('settings.settings_page') }}">
      {{ csrf_token_field() }}
      <label for="current_password">{{ _("Current password") }}:</label><br/>
      <input type="password" name="current_password" class="text input-width-full" /><br/>

      <label for="password1">{{ _("New password") }}:</label><br/>
      <input type="password" name="password1" class="text input-width-full" /><br/>

      <label for="password2">{{ _("Confirm new password") }}:</label><br/>
      <input type="password" name="password2" class="text input-width-full" /><br/>

      <input type="submit" class="button button-primary" value="{{ _('Apply') }}" />
</form>
{% endblock %}

smilepack/templates/simple_page.html
<!DOCTYPE html>
<html>
<head>
{%- block head %}
  <meta charset="utf-8" />
  <title>{% block title %}{{ _('Smilepack') }}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=yes" />
  {{ favicon_link_tag() }}
  {{ stylesheet_tag("simplepage_css") | safe }}
{%- endblock %}
</head>
<body>
<div class="wrap">
{% block body %}
<div class="modal">{% block modal_body %}{% endblock %}</div>
{% endblock %}
</div>
</body>
</html>

smilepack/templates/view.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <title>{{ pack.name or pack.hid }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=yes" />
    {{ favicon_link_tag() }}
    {{ stylesheet_tag("base_css") | safe }}
    {{ stylesheet_tag("widget_collection_css") | safe }}
</head>
<body>

<div class="top">
    <div class="header">
        <span class="page-title">
            <a href="{{ url_for('pages.index') }}" id="index_link">{{ _("Smilepack") }}</a>
            <span id="smp-name">"{{ (pack.name or pack.hid) }}"</span>
        </span>
    </div>
</div>

<div class="container widget-collection" id="smilepack">
    <div style="text-align: center" class="temporary"><img src="{{ asset_url_for('images/loading.gif') }}" alt="" /></div>
    <div class="collection-title">{{ _("Smilepack") }}</div>
    <div class="tabs-wrapper"></div>

    <div class="collection-message">{{ _("Choice a category of smilepack to view smiles") }}</div>
    <div class="collection-smiles"></div>
</div><!-- /container -->


{{ javascript_tag("viewer_js") | safe }}
<script>
viewer.smilepackData = {{ pack.bl.as_json(with_smiles=True)|tojson|safe }};
</script>
</body>
</html>